### ISSUE TITLE
Motion detection

### ISSUE THREAD

**Issue by m-rossi** [moritzmhmk/homebridge-camera-rpi#8]
Do you think it is possible to also perform a motion detection using [motion](https://github.com/Motion-Project/motion) and therefore also add a motion detection accessory to HomeKit?

**Comment by moritzmhmk** [comment]
Motion would need to stop using the camera whenever Homebridge needs access. So some kind of management would be necessary. Aside from that creating a motion detection accessory placed in the same room should work.

**Comment by idcrook** [comment]
For the camera view, would it be possible in this scenario to instead direct homebridge to an mjpeg stream created by `motion` itself?

a typical `motion` install can also set up an http streaming server at port 8080/8081 in addition to detecting motion. In that case, it could be treated like any other IP cam, so I think a homebridge plugin such as https://github.com/KhaosT/homebridge-camera-ffmpeg would apply for the image streaming view?

**Comment by moritzmhmk** [comment]
That would be possible but the performance would suffer a lot.

This project has the goal to get a decent performance on a Pi (zero).

**Comment by leonardpitzu** [comment]
i tried using motion (the app) - it works as expected (video streaming, motion detection, notification upon motion detection). the performance is terrible. even with a very low resolution things work very bad. it's basically useless on a pi zero. and i don't want to use a pi3 due to physical space constraints.

Given these can you please extend this plugin with a gpio triggered image notification on homebridge - aka. gpio goes low, a picture is "shot" and sent as a notification to the phone (homebridge takes care of this). if you would have such a mechanism i could add a motion detection sensor which toggles a gpio and the issue is solved. even more, the motion sensor, via gpio, can be exposed as a motion sensor in homekit. what do you think?

**Comment by moritzmhmk** [comment]
Plugins like [the one mentioned above](https://github.com/Killerameise/homebridge-infrared-motion-sesnor-gpio) should do the job just by placing them in the same room in the Home App.
